#' Simulated persistence meta-analysis
#'
#' A simulated meta-analysis of 60 studies reporting 1 to 5 pairs of endline
#' and follow-up effect sizes each, generated by [gh_simulate()] (see
#' `data-raw/persist_sim.R`). Each pair comes from a simulated two-arm trial
#' of 40 to 200 participants whose outcome has a test-retest correlation
#' `rho` drawn from a Beta(6, 3) distribution (mean 0.67).
#'
#' The data-generating values are `mu = 0.4`, `alpha = 0`, `beta = 0.4`,
#' `sd_u1 = 0.15`, `sd_u2 = 0.05`, `tau1 = 0.15`, and `tau2 = 0.05`, so 40% of
#' an endline effect persists to follow-up.
#'
#' @format A data frame with one row per pair of effect sizes:
#' \describe{
#'   \item{study}{study identifier}
#'   \item{es_id}{effect-size pair identifier}
#'   \item{n}{participants in the trial}
#'   \item{rho}{test-retest correlation of the outcome, which is also the
#'     sampling correlation of `es1` and `es2`}
#'   \item{es1, se1}{endline effect size and its standard error}
#'   \item{es2, se2}{follow-up effect size and its standard error}
#'   \item{theta1, theta2}{true endline and follow-up effects}
#' }
#' @source Simulated; see `data-raw/persist_sim.R` in the package source.
"persist_sim"
